services:
  - type: web
    name: laraclient
    env: docker
    plan: free
    repo: https://github.com/programaciontemporal/Examen-MF0493_3.git
    branch: master
    rootDir: .
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
